# Generated by Django 5.2.6 on 2025-09-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name', max_length=100)),
                ('dob', models.DateField(help_text='Enter Date of Birth')),
                ('age', models.IntegerField(help_text='Enter age from 18 to 22')),
                ('course_name', models.CharField(help_text='Enter your course', max_length=100)),
                ('department', models.CharField(help_text='Enter your department', max_length=100)),
                ('reg_no', models.IntegerField(help_text='Enter your register number')),
            ],
        ),
    ]
